/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;



import Clases.Conductor;
import Clases.ConductorProcess;
import Clases.Cronometro;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*******************************************************************************
# Nombre : Juan Diego Naranjo
# Fecha  : 2014/06/20
# JDNaranjo: Formulario principal
*******************************************************************************/

public class ConductorForm extends javax.swing.JFrame {

    /**
     * Creates new form ConductorForm
     */
    public ConductorForm() {
        initComponents();
        setControlVisibility(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processCB = new javax.swing.JComboBox();
        ConductoresLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        mailLbl = new javax.swing.JLabel();
        idTB = new javax.swing.JTextField();
        nameTB = new javax.swing.JTextField();
        phoneTB = new javax.swing.JTextField();
        mailTB = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        processCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- seleccione --", "INGRESAR", "BUSCAR", "BORRAR" }));
        processCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processCBActionPerformed(evt);
            }
        });

        ConductoresLbl.setText("CONDUCTORES");

        idLbl.setText("Cédula:");

        nameLbl.setText("Nombre");

        phoneLbl.setText("Teléfono:");

        mailLbl.setText("Correo:");

        okBtn.setText("Aceptar");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(ConductoresLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLbl)
                                .addGap(18, 18, 18)
                                .addComponent(idTB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(processCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLbl)
                                .addGap(18, 18, 18)
                                .addComponent(nameTB, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phoneTB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mailLbl)
                                .addGap(18, 18, 18)
                                .addComponent(mailTB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(okBtn)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConductoresLbl)
                .addGap(26, 26, 26)
                .addComponent(processCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl)
                    .addComponent(idTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(phoneTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailLbl)
                    .addComponent(mailTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okBtn)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processCBActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String process = (String)cb.getSelectedItem();
        switch (process){
            case "BUSCAR":
                setControlVisibility(false);
                idLbl.setVisible(true);
                idTB.setVisible(true);
            break;
            
            case "BORRAR":
                setControlVisibility(false);
                idLbl.setVisible(true);
                idTB.setVisible(true);
            break;
            
            case "INGRESAR":
                setControlVisibility(true);
            break;
            
            default: 
                setControlVisibility(false);
                break;
        }
    }//GEN-LAST:event_processCBActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        String process = (String)processCB.getSelectedItem();
        List<String> rowList =  new ArrayList<String>();
        Conductor conductor;
        ConductorProcess conductorProcess;        
        Cronometro cronometro = new Cronometro();        
        cronometro.start();
        
        switch (process){
            case "BUSCAR":
                conductor = new Conductor(idTB.getText());
                conductorProcess = new ConductorProcess(conductor, "SELECT");                                
                conductorProcess.run();
                rowList = conductorProcess.getRow();
                
                if(!rowList.isEmpty()){ //Usar debugger si no funciona
                    setControlVisibility(true);
                    fillFields(rowList);
                    JOptionPane.showMessageDialog(rootPane, "Proceso completado exitosamente.");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Registro no existe.");
                }
            break;
            
            case "BORRAR":
                conductor = new Conductor(idTB.getText());
                conductorProcess = new ConductorProcess(conductor, "DELETE");
                conductorProcess.run();
                JOptionPane.showMessageDialog(rootPane, "Eliminado correctamente");
            break;
            
            case "INGRESAR":
                conductor = new Conductor(idTB.getText(), nameTB.getText(), 
                        mailTB.getText(), phoneTB.getText());
                conductorProcess = new ConductorProcess(conductor, "INSERT");
                conductorProcess.run();
                JOptionPane.showMessageDialog(rootPane, "Ingresado correctamente");
            break;
            
            default: 
                JOptionPane.showMessageDialog(rootPane, "Seleccione una opción");
                break;
        }
        
        JOptionPane.showMessageDialog(rootPane, "Tiempo total " + cronometro.getTiempo());
    }//GEN-LAST:event_okBtnActionPerformed
      
    public void fillFields(List<String> _rowList){
        idTB.setText(_rowList.get(0));
        mailTB.setText(_rowList.get(1));
        phoneTB.setText(_rowList.get(2));
        nameTB.setText(_rowList.get(3));        
    }
    
    public void setControlVisibility(boolean _visible){
        idLbl.setVisible(_visible);
        idTB.setVisible(_visible);
        nameLbl.setVisible(_visible);                
        nameTB.setVisible(_visible);
        mailLbl.setVisible(_visible);
        mailTB.setVisible(_visible);
        phoneLbl.setVisible(_visible); 
        phoneTB.setVisible(_visible);
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConductorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConductorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConductorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConductorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConductorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConductoresLbl;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTB;
    private javax.swing.JLabel mailLbl;
    private javax.swing.JTextField mailTB;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTB;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTB;
    private javax.swing.JComboBox processCB;
    // End of variables declaration//GEN-END:variables
}
